### ISSUE TITLE
Remove email-validation-util git submodule from the repo

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/email-validation-util#10]
* which looks accidentally added
Ref: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by m04116** [comment]
1. Make a branch: bugfix/rm-bogus-submodule.
2. Then on above branch I need: git rm -rf email-validation-util.
3. ~Git merge.~ PR

**Comment by m04116** [comment]
Closes #10:
* Removed email-validation-util git submodule
